name = "nuxt-ijustcc"
main = "./dist/server/index.mjs"
workers_dev = true
compatibility_date = "2022-09-10"
rules = [{ type = "ESModule", globs = ["**/*.js", "**/*.mjs"] }]

[site]
bucket = "dist/public"
