name: yml 格式的 post
description: 测试使用
title: "444"
labels: ["post"]
projects: []
assignees:
  - otto-j
body:
  - type: input
    id: perlink
    attributes:
      label: Permalink
      description:
      placeholder: title
    validations:
      required: true

  - type: textarea
    id: content
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true

  - type: dropdown
    id: tags
    attributes:
      label: 默认 tag
      multiple: true
      options:
        - 生活
        - 技术
        - 碎碎念
        - 读书
        - 电影
  - type: checkboxes
    id: status
    attributes:
      label: 发布状态
      description: 有些文章不希望立刻发布
      options:
        - label: 发布
